M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu22.04.1} date di 08 nov 2022 11:28:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-08T11:28:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X115.65Y-86.6
X158.65Y-86.6
T0
M30
